//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int ID { get; set; }
        public string Type_EmpCode { get; set; }
        public string EmployeeName { get; set; }
        public string MobileNumber { get; set; }
        public string Password { get; set; }
        public string EmailId { get; set; }
        public Nullable<int> RoleCode { get; set; }
        public Nullable<int> RightsCode { get; set; }
    }
}
